apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- with .Values.labels }}
    {{- toYaml . | nindent 8 }}
    {{- end }}
    app: tfy-sds-server
  name: tfy-oauth-secret
data:
  secrets.yaml: |-
      secrets:
        - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
          name: token
          generic_secret:
            secret:
              inline_string: {{ .Values.oauth.clientSecret }}
        - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
          name: hmac
          generic_secret:
            secret:
              inline_bytes: {{ .Values.oauth.hmac }}
