apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: sds-deployment
spec:
  selector:
    matchLabels:
      {{- with .Values.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      truefoundry.com/subcomponent: sds-server
  template:
    metadata:
      labels:
        {{- with .Values.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        truefoundry.com/subcomponent: sds-server
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: karpenter.sh/capacity-type
                operator: In
                values:
                  - spot
          weight: 100
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: karpenter.sh/capacity-type
                operator: In
                values:
                  - spot
                  - on-demand
  containers:
    - command:
        - /app/sds-server
        - '--port'
        - '8000'
        - '--file'
        - /secrets/secrets.yaml
      image: "{{ .Values.sdsServer.image.repository }}:{{ .Values.sdsServer.image.tag }}"
      imagePullPolicy: IfNotPresent
      name: sds-server
      ports:
        - containerPort: 8000
          name: port-8000
          protocol: TCP
      resources:
        limits:
          cpu: 0.02
          ephemeral-storage: 20M
          memory: 50M
        requests:
          cpu: 0.01
          ephemeral-storage: 10M
          memory: 30M
      volumeMounts:
        - mountPath: /secrets/secrets.yaml
          name: sds-config-map-volume
          subPath: secrets.yaml
  topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          truefoundry.com/component: sds-server
      maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
  volumes:
    - configMap:
        name: sds-config-map
      name: sds-config-map-volume
