{{- if .Values.tfyGateway }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.tfyGateway.name }}
  namespace: istio-system
spec: 
  {{- tpl (toYaml .Values.tfyGateway.spec) . | nindent 2 }}
{{- end }}
